 //data handling for DB seeding

 const dataTrimmer = function(data){
  let results = []
  data.forEach((datum) => {
    let temp = {};
    temp.id = datum.id;
    temp.seller = datum.seller;
    temp.rating = datum.rating / 2;
    results.push(temp);
  });
  console.log(results)
  return results;
}

const addReviews = function(data){
  data.forEach((datum) => {
    datum.reviews = []
  })
  console.log(data)
  return data;
}

const pushReviews = function(dataO, dataD){
  console.log(dataO[0].itemId)
  dataO.forEach((datum) => {
    let date = datum.createdAt.$date
    datum.createdAt = date;
    let temp = datum.itemId - 1;
    dataD[temp].reviews.push(datum);
  });
  return dataD;
}

const data =
[ { id: 1,
  seller: 'AmerisourceBergen Corporation (Holding Co)',
  rating: 1.5,
  reviews: [] },
{ id: 2,
  seller: 'Aptose Biosciences, Inc.',
  rating: 0.5,
  reviews: [] },
{ id: 3,
  seller: 'ProAssurance Corporation',
  rating: 2.5,
  reviews: [] },
{ id: 4, seller: 'Cempra, Inc.', rating: 3.5, reviews: [] },
{ id: 5, seller: 'Novavax, Inc.', rating: 3, reviews: [] },
{ id: 6, seller: 'Tesoro Logistics LP', rating: 4.5, reviews: [] },
{ id: 7,
  seller: 'Dynagas LNG Partners LP',
  rating: 5,
  reviews: [] },
{ id: 8,
  seller: 'General Finance Corporation',
  rating: 0.5,
  reviews: [] },
{ id: 9, seller: 'MBIA, Inc.', rating: 4.5, reviews: [] },
{ id: 10, seller: 'V.F. Corporation', rating: 1.5, reviews: [] },
{ id: 11,
  seller: 'First Savings Financial Group, Inc.',
  rating: 5,
  reviews: [] },
{ id: 12,
  seller: 'MFA Financial, Inc.',
  rating: 3.5,
  reviews: [] },
{ id: 13, seller: 'HV Bancorp, Inc.', rating: 3, reviews: [] },
{ id: 14, seller: 'Chimerix, Inc.', rating: 1, reviews: [] },
{ id: 15,
  seller: 'BlackRock Science and Technology Trust',
  rating: 0.5,
  reviews: [] },
{ id: 16, seller: 'Tesco Corporation', rating: 4.5, reviews: [] },
{ id: 17, seller: 'Gap, Inc. (The)', rating: 1.5, reviews: [] },
{ id: 18,
  seller: 'Covanta Holding Corporation',
  rating: 4,
  reviews: [] },
{ id: 19,
  seller: 'PowerShares DWA Basic Materials Momentum Portfolio',
  rating: 3.5,
  reviews: [] },
{ id: 20, seller: 'Genesco Inc.', rating: 1.5, reviews: [] },
{ id: 21,
  seller: 'Arch Capital Group Ltd.',
  rating: 5,
  reviews: [] },
{ id: 22,
  seller: 'National Grid Transco, PLC',
  rating: 4.5,
  reviews: [] },
{ id: 23,
  seller: 'Korea Equity Fund, Inc.',
  rating: 1.5,
  reviews: [] },
{ id: 24, seller: 'ShotSpotter, Inc.', rating: 1, reviews: [] },
{ id: 25, seller: 'ShotSpotter, Inc.', rating: 1, reviews: [] },
{ id: 26,
  seller: 'Cardiome Pharma Corporation',
  rating: 1.5,
  reviews: [] },
{ id: 27,
  seller: 'China Eastern Airlines Corporation Ltd.',
  rating: 2.5,
  reviews: [] },
{ id: 28, seller: 'Genie Energy Ltd.', rating: 3.5, reviews: [] },
{ id: 29,
  seller: 'Navios Maritime Holdings Inc.',
  rating: 3.5,
  reviews: [] },
{ id: 30,
  seller: 'Digimarc Corporation',
  rating: 1.5,
  reviews: [] },
{ id: 31,
  seller: 'Silvercrest Asset Management Group Inc.',
  rating: 4,
  reviews: [] },
{ id: 32, seller: 'iPass Inc.', rating: 2, reviews: [] },
{ id: 33,
  seller: 'Washington Prime Group Inc.',
  rating: 1.5,
  reviews: [] },
{ id: 34,
  seller: 'Boulevard Acquisition Corp. II',
  rating: 4.5,
  reviews: [] },
{ id: 35,
  seller: 'PowerShares S&P SmallCap Utilities Portfolio',
  rating: 0.5,
  reviews: [] },
{ id: 36, seller: 'US Ecology, Inc.', rating: 3.5, reviews: [] },
{ id: 37,
  seller: 'Apollo Commercial Real Estate Finance',
  rating: 0.5,
  reviews: [] },
{ id: 38, seller: 'CHS Inc', rating: 0.5, reviews: [] },
{ id: 39, seller: 'Plantronics, Inc.', rating: 5, reviews: [] },
{ id: 40,
  seller: 'Abercrombie & Fitch Company',
  rating: 4.5,
  reviews: [] },
{ id: 41, seller: 'B&G Foods, Inc.', rating: 4.5, reviews: [] },
{ id: 42,
  seller: 'VictoryShares Dividend Accelerator ETF',
  rating: 4,
  reviews: [] },
{ id: 43, seller: 'Orbotech Ltd.', rating: 4, reviews: [] },
{ id: 44, seller: 'j2 Global, Inc.', rating: 2.5, reviews: [] },
{ id: 45, seller: 'GWG Holdings, Inc', rating: 3.5, reviews: [] },
{ id: 46,
  seller: 'Banc of California, Inc.',
  rating: 4,
  reviews: [] },
{ id: 47,
  seller: 'Tupperware Brands Corporation',
  rating: 2,
  reviews: [] },
{ id: 48,
  seller: 'Federal Agricultural Mortgage Corporation',
  rating: 3,
  reviews: [] },
{ id: 49,
  seller: 'Eldorado Resorts, Inc.',
  rating: 5,
  reviews: [] },
{ id: 50, seller: 'OpGen, Inc.', rating: 2, reviews: [] },
{ id: 51,
  seller: 'Saban Capital Acquisition Corp.',
  rating: 3,
  reviews: [] },
{ id: 52, seller: 'iRadimed Corporation', rating: 5, reviews: [] },
{ id: 53,
  seller: 'Las Vegas Sands Corp.',
  rating: 1.5,
  reviews: [] },
{ id: 54,
  seller: 'America\'s Car-Mart, Inc.',
  rating: 4,
  reviews: [] },
{ id: 55, seller: 'Teradyne, Inc.', rating: 3.5, reviews: [] },
{ id: 56, seller: 'Bioblast Pharma Ltd.', rating: 4, reviews: [] },
{ id: 57,
  seller: 'Cohen & Steers Global Income Builder, Inc.',
  rating: 4.5,
  reviews: [] },
{ id: 58,
  seller: 'Schweitzer-Mauduit International, Inc.',
  rating: 1,
  reviews: [] },
{ id: 59,
  seller: 'OncoGenex Pharmaceuticals Inc.',
  rating: 3,
  reviews: [] },
{ id: 60,
  seller: 'Mirna Therapeutics, Inc.',
  rating: 1.5,
  reviews: [] },
{ id: 61,
  seller: 'Nuveen Preferred and Income 2022 Term Fund',
  rating: 2.5,
  reviews: [] },
{ id: 62, seller: 'PBF Energy Inc.', rating: 3, reviews: [] },
{ id: 63, seller: 'Badger Meter, Inc.', rating: 3, reviews: [] },
{ id: 64,
  seller: 'VelocityShares VIX Short-Term ETN',
  rating: 2,
  reviews: [] },
{ id: 65,
  seller: 'Global X Millennials Thematic ETF',
  rating: 5,
  reviews: [] },
{ id: 66,
  seller: 'American Vanguard Corporation',
  rating: 3.5,
  reviews: [] },
{ id: 67,
  seller: 'Barington/Hilco Acquisition Corp.',
  rating: 0.5,
  reviews: [] },
{ id: 68,
  seller: 'Viper Energy Partners LP',
  rating: 0.5,
  reviews: [] },
{ id: 69, seller: 'NRG Yield, Inc.', rating: 2.5, reviews: [] },
{ id: 70, seller: 'Enel Americas S.A.', rating: 5, reviews: [] },
{ id: 71, seller: 'Heico Corporation', rating: 4.5, reviews: [] },
{ id: 72,
  seller: 'Motorcar Parts of America, Inc.',
  rating: 4,
  reviews: [] },
{ id: 73, seller: 'Herbalife LTD.', rating: 0.5, reviews: [] },
{ id: 74,
  seller: 'Origin Agritech Limited',
  rating: 3,
  reviews: [] },
{ id: 75,
  seller: 'MainSource Financial Group, Inc.',
  rating: 0.5,
  reviews: [] },
{ id: 76,
  seller: 'Diamond Offshore Drilling, Inc.',
  rating: 2.5,
  reviews: [] },
{ id: 77,
  seller: 'Tanger Factory Outlet Centers, Inc.',
  rating: 2.5,
  reviews: [] },
{ id: 78,
  seller: 'Guidewire Software, Inc.',
  rating: 1.5,
  reviews: [] },
{ id: 79,
  seller: 'FactSet Research Systems Inc.',
  rating: 2.5,
  reviews: [] },
{ id: 80,
  seller: 'Eagle Bulk Shipping Inc.',
  rating: 4,
  reviews: [] },
{ id: 81,
  seller: 'China HGS Real Estate, Inc.',
  rating: 1,
  reviews: [] },
{ id: 82,
  seller: 'Wells Fargo & Company',
  rating: 3,
  reviews: [] },
{ id: 83,
  seller: 'John Hancock Financial Opportunities Fund',
  rating: 2.5,
  reviews: [] },
{ id: 84, seller: 'BP p.l.c.', rating: 3, reviews: [] },
{ id: 85, seller: 'CubeSmart', rating: 4.5, reviews: [] },
{ id: 86, seller: 'EnerNOC, Inc.', rating: 5, reviews: [] },
{ id: 87,
  seller: 'LaSalle Hotel Properties',
  rating: 4,
  reviews: [] },
{ id: 88, seller: 'Tenaris S.A.', rating: 0.5, reviews: [] },
{ id: 89,
  seller: 'RCI Hospitality Holdings, Inc.',
  rating: 5,
  reviews: [] },
{ id: 90,
  seller: 'WisdomTree U.S. SmallCap Quality Dividend Growth Fund',
  rating: 5,
  reviews: [] },
{ id: 91,
  seller: 'The AES Corporation',
  rating: 1.5,
  reviews: [] },
{ id: 92,
  seller: 'Verizon Communications Inc.',
  rating: 2.5,
  reviews: [] },
{ id: 93, seller: 'Seadrill Limited', rating: 0.5, reviews: [] },
{ id: 94, seller: 'HealthStream, Inc.', rating: 4, reviews: [] },
{ id: 95, seller: 'DHT Holdings, Inc.', rating: 2, reviews: [] },
{ id: 96,
  seller: 'Controladora Vuela Compania de Aviacion, S.A.B. de C.V.',
  rating: 1.5,
  reviews: [] },
{ id: 97, seller: 'CyrusOne Inc', rating: 3.5, reviews: [] },
{ id: 98, seller: 'The Obesity ETF', rating: 0.5, reviews: [] },
{ id: 99,
  seller: 'Assured Guaranty Ltd.',
  rating: 1,
  reviews: [] },
{ id: 100,
  seller: 'Industrial Services of America, Inc.',
  rating: 1,
  reviews: [] } ]

module.exports = {data:data, dataTrimmer:dataTrimmer, addReviews:addReviews, pushReviews:pushReviews}